### ISSUE TITLE
Inline comments in code tab missing first comment

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#13528]
On the conversation tab (https://gitea.com/macaron/i18n/pulls/7):

<img width="844" alt="image" src="https://user-images.githubusercontent.com/115237/98907311-eb008c80-24be-11eb-9060-c4fe7e72923c.png">

On the code tab (https://gitea.com/macaron/i18n/pulls/7/files):

<img width="667" alt="image" src="https://user-images.githubusercontent.com/115237/98907350-fc499900-24be-11eb-9cbf-f1fef9ad6176.png">

**Comment by lafriks** [comment]
yaeh I think this happens when commet becomes outdated?

**Comment by zeripath** [comment]
And should have been fixed by #13448

**Comment by silverwind** [comment]
Don't think it's fixe. gitea.com is at https://github.com/go-gitea/gitea/commit/5d932b35ca4ef56525b815961d7f4f48a5119875 which should include your fix from https://github.com/go-gitea/gitea/commit/b091c994b5930829b690aedbcf2945198240706b but I still see the issue in the linked example.
