### ISSUE TITLE
High cpu comsuming cause gitea very slow

### ISSUE THREAD

**Issue by 0000005** [go-gitea/gitea#15143]
- Gitea version (or commit ref): 1.13.2
- Git version: 1.8.3.1
- Operating system:
  
  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No
- Log gist:

## Description

...
I don't know what action will be causing this problem yet. But it happened frequently.

## Screenshots
![image](https://user-images.githubusercontent.com/9690089/112288956-d2a04a00-8cc8-11eb-82df-bcaf8cf6ec9e.png)
![image](https://user-images.githubusercontent.com/9690089/112289154-024f5200-8cc9-11eb-984e-1f4c63ad9fa3.png)
The cpu high usage will last for tens of minutes.

**Comment by 81519434** [comment]
I found some related issue. https://github.com/go-gitea/gitea/issues/9642

**Comment by zeripath** [comment]
Please update - this is likely fixed by #14649 which is in 1.13.3

**Comment by zeripath** [comment]
The latest point release for 1.13 is 1.13.6 - you should always try the latest point release.

**Comment by 81519434** [comment]
Thank you.
I will try the latest stable version to see if the problem remains.

**Comment by techknowlogick** [comment]
Closing, please re-open if it remains.

**Comment by 81519434** [comment]
Please re-open this issue, because after upgrade to 1.13.6 the problem remains.

**Comment by 81519434** [comment]
![image](https://user-images.githubusercontent.com/9690089/112410842-d5e21700-8d56-11eb-85e6-2148e29f8dfe.png)

**Comment by 81519434** [comment]
tree model
![image](https://user-images.githubusercontent.com/9690089/112411027-2ce7ec00-8d57-11eb-8d2a-219dca703558.png)

**Comment by 81519434** [comment]
@techknowlogick

**Comment by 81519434** [comment]
what should i do?

**Comment by 81519434** [comment]
I am pretty sure that merge pr will cause this problem, although this pr is very small.
![image](https://user-images.githubusercontent.com/9690089/112435356-954ac380-8d7f-11eb-8f61-bd08414fd3e0.png)

**Comment by noerw** [comment]
The PR may be small, but does that repo have a long history (i.e. > 10.000 commits)?

**Comment by 81519434** [comment]
> The PR may be small, but does that repo have a long history (i.e. > 10.000 commits)?

![image](https://user-images.githubusercontent.com/9690089/112606255-1e7efa80-8e53-11eb-9e99-911d4c695075.png)

**Comment by 81519434** [comment]
It is very fast if I merge the branch in the local.

**Comment by zeripath** [comment]
I think pprof would be useful here:

```ini
[server]
ENABLE_PPROF = true
```

Just before the slow merge please start:

`wget -O cpuprofile.out http://localhost:6060/debug/pprof/profile?seconds=60`

Then do the merge and either attach the profile here or talk to me on discord.

I will need to know what version of gitea you are running exactly.

**Comment by 81519434** [comment]
[cpuprofile.zip](https://github.com/go-gitea/gitea/files/6226981/cpuprofile.zip)

**Comment by 81519434** [comment]
[gitea.0330.log](https://github.com/go-gitea/gitea/files/6227043/gitea.0330.log)
merge action happend at 2021-03-30 14:35:38

**Comment by 81519434** [comment]
@zeripath Can you analyze this problem for me? thank you very much!

**Comment by zeripath** [comment]
OK you've only sent me the xorm logs which are the least useful logs. Please read: https://docs.gitea.io/en-us/logging-configuration/#debugging-problems.

And the profile doesn't actually contain all of the merge - however, it probably does show where the inefficiency is:

43% of the time in that profile is spent in https://github.com/go-gitea/gitea/blob/6dfa92bb1ca97d4e93e07dd5c289a8035761d89c/modules/git/repo_language_stats.go#L23-L91

In particular 27.3% (3.46s) is spent in go-enry.IsVendor:

```
// IsVendor returns whether or not path is a vendor path.
func IsVendor(path string) bool {
	return matchRegexSlice(data.VendorMatchers, path)
}
```

Which is remarkably inefficiently written because it simply iterates over a list of regexps checking each one in turn without combining the regexps in to a single regexp. 

There are a number of other inefficiencies that this flame graph identifies but I think this is a particularly glaring issue.

**Comment by zeripath** [comment]
@81519434 would it be possible to for you give us a profile file for this push on 1.14-rc2 and master?

(I think at least a few things should have been improved even without the isvendor pr I've proposed above but it would be good to know for sure.)

**Comment by 81519434** [comment]
We can see `git rev-list` is the reason why CPU keeps high consumption from the `htop`.
Is that mean `gitea` incorrectly triggered the git command line?
If it is like this, I think that `pprof` will not find the cause. Because git command line is not managed by `go`.
Of course, I am not familiar with `go`. This is all my guess.

**Comment by johanvdw** [comment]
What happens if you create a new repo on the same server, push the original data and open the same pull request? Your git directory (on the server) might be damaged if git itself is very slow.

More recent versions of git also contain speedups to the mentioned functions, but it should be a fast operation anyway.

**Comment by 81519434** [comment]
I will try to upgrade the latest git client verstion, and see if the problem remains.

**Comment by wxiaoguang** [comment]
@0000005 Has the problem been resolved? Since Gitea 1.16 is coming and a lot of code was changed(improved), I think we can close this one. If there is any performance problem, we can continue to improve on 1.16
