### ISSUE TITLE
Updated xx days ago displays wrong in other languages than english

### ISSUE THREAD

**Issue by watschi** [go-gitea/gitea#2098]
- Gitea version (or commit ref): f99489d5c522663cfc14b9b65539966844f3ee6b (current master)
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL) https://try.gitea.io/explore/repos
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When switching to another language than english the last update date gets displayed wrong:
`Aktualisiert vor%!(EXTRA string=%s 1 Tag)`
I've tried a few different languages with the same result.

It happens in "explore" view aswell as in a repository.

## Screenshots

English:
![image](https://user-images.githubusercontent.com/26351931/27769640-d21e4706-5f2e-11e7-8548-d61271c8423f.png)

German:
![image](https://user-images.githubusercontent.com/26351931/27769643-e22f269c-5f2e-11e7-9e05-6b323fe76613.png)

Spanish (inside a repo):
![image](https://user-images.githubusercontent.com/26351931/27769664-6bdf6d16-5f2f-11e7-8b18-392b15d21776.png)

**Comment by lafriks** [comment]
It is known issue until we update language files from crowdin. It is work in progress already

**Comment by bkcsoft** [comment]
@lafriks Dont' close the issue until it's fixed. Otherwise we'll just get duplicates 😉

**Comment by bkcsoft** [comment]
Should be fixed in https://github.com/go-gitea/gitea/pull/2104

**Comment by otih** [comment]
still open with 1.3.0-dev (a4cd4616c6f8524f8eb79d6184e855b3a8164130):
ago%!(EXTRA string=1 year %s)

**Comment by lunny** [comment]
@otih could you give some example on https://try.gitea.io?

**Comment by otih** [comment]
https://git.okoyono.de/mezzomix/buch_des_monats

**Comment by f0086** [comment]
Why is this closed? The problem remains. See last post from @otih 
Is there some cache to clear?
I've tried the following:

```
make clean
make update-translations
make build
./gitea web
```

**Comment by lafriks** [comment]
What version are you building?

**Comment by f0086** [comment]
git master
I just pulled it 30 minutes ago.

Some hints to debug this would be great to isolate the problem.
(We switched our installation from gogs to gitea if that helps)

**Comment by lafriks** [comment]
That can't be... what language?

**Comment by otih** [comment]
Hi, what do you mean with "what language"? Please check the provided link: https://git.okoyono.de/mezzomix/buch_des_monats

© Gitea Version: 1.1.0+909-g515cdaa8
Go1.8.3

**Comment by lunny** [comment]
@f0086 `make update-translations` is unnecessary any more.

**Comment by lunny** [comment]
And https://try.gitea.io/lunny/buch_des_monats is OK.
