### ISSUE TITLE
JS error on action run page

### ISSUE THREAD

**Issue by denyskon** [go-gitea/gitea#27213]
### Description

[Bildschirmaufzeichnung vom 2023-09-23, 17-34-22.webm](https://github.com/go-gitea/gitea/assets/47871822/6045d6ed-bb63-4e39-aa19-303b21f4d2d6)

Switching from an action run page to another page, an error appears saying `JavaScript promise rejection: TypeError: t is undefined`

### Gitea Version

1.21.0-rc0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Docker-Compose

### Database

SQLite

**Comment by lng2020** [comment]
Could you provide more detailed information in the Chrome dev console about where the error occurs?

**Comment by silverwind** [comment]
Need a stack trace and/or screenshot of surrounding code in devtools. You will need to check "Persist Log" in the devtools console so it persists across page reload.

BTW I fixed a similar bug in https://github.com/go-gitea/gitea/pull/26985, but I think this one is different.

**Comment by denyskon** [comment]
![grafik](https://github.com/go-gitea/gitea/assets/47871822/f58fdaa5-0d9d-4783-99e6-64adc904eaef)

That's everything I get. Do you have any other suggestions how to narrow it down?

**Comment by silverwind** [comment]
Click on the index.js link top right, then find the button to pretty-print the source and screenshot that. From the stack trace I can see it happens in `loadJob`.

**Comment by wxiaoguang** [comment]
> BTW I fixed a similar bug in #26985, but I think this one is different.

Because #26985 has bug. You missed a `return` in the `catch`

**Comment by denyskon** [comment]
![grafik](https://github.com/go-gitea/gitea/assets/47871822/6cbec1e4-66eb-4213-a2c7-f4a5e25682a8)
Seems to be exactly where you introduced the fetch wrapper...

**Comment by silverwind** [comment]
Oops, yes that should have a return. The error message is odd but I'm pretty sure the return will fix it and this is a network error you are seeing.
