### ISSUE TITLE
Integration between drone and Gitea (bleeding edge) erroring out on webhook

### ISSUE THREAD

**Issue by techknowlogick** [go-gitea/gitea#2824]
- Gitea version (or commit ref): e6a97b6
- Git version: 2.13.5
- Operating system: centos (Docker)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
## Description
When I push a commit to a repo that has a webhook that is connected to drone the webhook fails. Checking the logs from gitea I see that drone fetches a URL from the API, but is returned a 404 (not found) error.
I've tested calling that route directly via browser and I also get a 404. However when I call /api/v1/repos/sdstack/atomic/ directly via my browser (when I am logged in) I get information about the repo, and when I am logged out (testing via incognito mode) I call the /api/v1/repos/sdstack/atomic/ URL and it gives me an expected 403 (as it is a private repo so I wouldn't want someone not logged in to be able to get that information). 

Drone version: 0.8.1+build.1318

172.18.0.100 - - [01/Nov/2017:20:39:28 +0300] "GET /api/v1/repos/sdstack/atomic/raw/6d31739044602484ef3b658270a973c5ebedb461/.drone.yml HTTP/1.1" 404 11349 "-" "Go-http-client/1.1" "-"

**Comment by techknowlogick** [comment]
Just confirmed this happens on latest commit of gitea 122a66f

[Macaron] 2017-11-02 03:12:13: Started GET /api/v1/repos/whff/whff/raw/ad61956db6300cad2d0f72fbe4c5128f041c05dc/.drone.yml for 172.18.0.100
[Macaron] 2017-11-02 03:12:13: Completed /api/v1/repos/whff/whff/raw/ad61956db6300cad2d0f72fbe4c5128f041c05dc/.drone.yml 404 Not Found in 9.807562ms

**Comment by lflare** [comment]
I would like to confirm that I have the same odd issue.

EDIT: Not sure if this is relevant? https://github.com/drone/drone/commit/517c003af2d9043f4cdd0fb280cb4776250d3f0f

**Comment by lafriks** [comment]
@LFlare it should not be related

**Comment by lflare** [comment]
@lafriks, I've tried using my front-end web proxy to dynamically rewrite the URLs on-the-go and from what I found out, accessing the API endpoint over web browser and having it rewrote works **but** having drone access the API endpoint to query for `.drone.yml` and having it rewrote does **not** work. Since Gitea responds to unauthenticated access to private repositories with a _404_, I feel like it might have some relevance.

To that extent, I'm still scrolling through the code trying to figure out what changed recently that screwed up the integration. 

EDIT: I believe I've found the issue @ 513375c429435ba60a667b219bdfb00e5b760b38. Working out a hotfix now.

**Comment by lflare** [comment]
@lafriks, @techknowlogick, this has been fixed in #2836.

**Comment by strk** [comment]
is Gitea-1.2.3 immune from this ?

**Comment by lafriks** [comment]
@strk yes it was broken on master

**Comment by quantonganh** [comment]
I upgraded Gitea to version 1.4.0+rc2-3-g5d0c987 but still see this in the logs:

```
[Macaron] 2018-03-12 09:05:48: Started GET /api/v1/repos/org/repo/raw/refs/pull/70/head/.drone.yml for 172.18.0.1
[Macaron] 2018-03-12 09:05:48: Completed GET /api/v1/repos/org/repo/raw/refs/pull/70/head/.drone.yml 404 Not Found in 63.545961ms
```

**Comment by selewu** [comment]
I upgraded Gitea to version 1.9 but still see this in the logs:
`[Macaron] 2019-09-05 08:12:33: Started GET /api/v1/repos/chaplin/xshop_new/raw/eaeb7e075e42001b97b89b348cd2df31156bf1aa/.drone.yml for 192.168.0.31`
`[Macaron] 2019-09-05 08:12:33: Completed GET /api/v1/repos/chaplin/xshop_new/raw/eaeb7e075e42001b97b89b348cd2df31156bf1aa/.drone.yml 404 Not Found in 78.427818ms`
