### ISSUE TITLE
[Summary] Loading user dashboard too slow

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#31698]
### Feature Description

We have received may reports about loading user dashboard too slow.
Please discuss/report related/similar issues (only the user dashboard, other pages are fine) in this summary, and avoid creating more and more.
Although these reports maybe caused by different reasons, I think it is better to have a summary about this issue.
@lunny
Can you pin this issue on the top?

Opening:
- #29769
- #32858

Closed:
- #16665
- #21045
- #21611
- #23101
- #31582
- #31646
- #32112
- #32224

**Comment by lunny** [comment]
#32110 should resolve the problem.

**Comment by yp05327** [comment]
Hope it works.

**Comment by lunny** [comment]
#32127 should resolve the problem for most Gitea instances.

**Comment by yp05327** [comment]
Still got report after upgrade to the latest version.

**Comment by uxbug** [comment]
update 1.23.3 dashboard also too slow

- docker install
- database: sqlite
- git version 2.47.2
- Gitea version: 1.23.3 built with GNU Make 4.4.1, go1.23.6 : bindata, timetzdata, sqlite, sqlite_unlock_notify
- log
```
2025/02/13 07:29:03 ...s/graceful/server.go:50:NewServer() [I] Starting new Web server: tcp:0.0.0.0:3000 on PID: 18

2025/02/13 07:29:15 ...eb/routing/logger.go:68:func1() [W] router: slow      GET / for 1x.1x.x.x3:0, elapsed 3424.7ms @ web/home.go:32(web.Home)

2025/02/13 07:30:49 models/db/list.go:210:]() [W] [Slow SQL Query] SELECT `id`, `repo_id`, `schedule_id`, `next`, `prev`, `spec`, `created`, `updated` FROM `action_schedule_spec` WHERE next<=? ORDER BY `id` DESC LIMIT 50 [1739431803] - 46.067580691s

2025/02/13 07:30:49 ...eb/routing/logger.go:102:func1() [I] router: completed GET / for 1x.1x.x.x3:0, 200 OK in 97507.5ms @ web/home.go:32(web.Home)

2025/02/13 07:30:49 ...eb/routing/logger.go:102:func1() [I] router: completed GET /repo/search?count_only=1&uid=1&team_id=undefined&q=&page=1&mode= for 1x.1x.x.x3:0, 200 OK in 46.7ms @ repo/repo.go:573(repo.SearchRepo)

2025/02/13 07:30:50 ...eb/routing/logger.go:102:func1() [I] router: completed GET /repo/search?sort=updated&order=desc&uid=1&team_id=undefined&q=&page=1&limit=15&mode=&archived=false for 1x.1x.x.x3:0, 200 OK in 693.8ms @ repo/repo.go:573(repo.SearchRepo)
```

- doctor check result
```
9a8546a05926:~$ gitea doctor check --run check-db-consistency

[1] Check consistency of database
OK

All done (checks: 1).
```

**Comment by AlliotTech** [comment]
Hi guys, any update about this issue?

v1.23.7 still have this issue: 
```
gitea  | 2025/04/28 22:44:51 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/login for 192.168.208.1:57392, 303 See Other in 161.7ms @ auth/auth.go:180(auth.SignIn)
gitea  | 2025/04/28 22:44:54 ...eb/routing/logger.go:68:func1() [W] router: slow      GET / for 192.168.208.1:57406, elapsed 3356.5ms @ web/home.go:32(web.Home)





gitea  | 2025/04/28 22:45:50 models/db/list.go:210:]() [W] [Slow SQL Query] SELECT `id`, `repo_id`, `schedule_id`, `next`, `prev`, `spec`, `created`, `updated` FROM `action_schedule_spec` WHERE next<=? ORDER BY `id` DESC LIMIT 50 [1745851529] - 21.397119388s
```

**Comment by lunny** [comment]
#33981 should fix this. Please wait v1.24

**Comment by AlliotTech** [comment]
> [#33981](https://github.com/go-gitea/gitea/pull/33981) should fix this. Please wait v1.24

Thank you. I am currently fixing it by adding the following configuration to the app.ini:
```
[cron.delete_old_actions]
ENABLED = true
RUN_AT_START = true
NOTICE_ON_SUCCESS = true
```

**Comment by lunny** [comment]
> > [#33981](https://github.com/go-gitea/gitea/pull/33981) should fix this. Please wait v1.24
> 
> Thank you. I am currently fixing it by adding the following configuration to the app.ini:
> 
> ```
> [cron.delete_old_actions]
> ENABLED = true
> RUN_AT_START = true
> NOTICE_ON_SUCCESS = true
> ```

That should be a backend task which should not be considered as slow.
